### ISSUE TITLE
LSPDFR/RPH Compatibility with Map Editor Issue

### ISSUE THREAD

**Issue by CptLevi23** [oldnapalm/MapEditor#3]
I would like to know if this is possible to load a mansion while using LSPDFR? Every time I have tried to load a mansion with map editor while running LSPDFR, it gives me this exception:
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MapEditor.MapEditor.LoadMap(String filename, Format format)

I ran the game without Rage Plugin Hook, and loaded the mansions just fine. But with RPH and or LSPDFR gives me that error.
[ScriptHookVDotNet.log](https://github.com/oldnapalm/MapEditor/files/7843116/ScriptHookVDotNet.log)
[MapEditor.log](https://github.com/oldnapalm/MapEditor/files/7843119/MapEditor.log)

**Comment by oldnapalm** [comment]
Can you run this version and send me a new log? Put both files (dll and pdb) in scripts folder.

[MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/7846131/MapEditor.zip)

**Comment by CptLevi23** [comment]
ok, I will do this after work. thx.

**Comment by CptLevi23** [comment]
So, it did it again. Same exception error. 
[MapEditor.log](https://github.com/oldnapalm/MapEditor/files/7850085/MapEditor.log)
[ScriptHookVDotNet.log](https://github.com/oldnapalm/MapEditor/files/7850086/ScriptHookVDotNet.log)

**Comment by oldnapalm** [comment]
Yes, same error was expected, but now it gives the line number in the log.

Can you test this please?

[MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/7850138/MapEditor.zip)

**Comment by CptLevi23** [comment]
yes, do I need to use the new .zip file u just sent?

**Comment by oldnapalm** [comment]
Use this one instead, I changed other place which may have the same issue

[MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/7850378/MapEditor.zip)

Post the new log if you still have problem, only the part with the line number is enough, e.g.

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MapEditor.MapEditor.LoadMap(String filename, Format format) in C:\Users\Cassio\source\repos\MapEditor\MapEditor.cs:line 751
```

**Comment by CptLevi23** [comment]
Ok, so it worked but, when the galieo1,2and3.xml loaded it looked all distorted and everywhere.  
 at MapEditor.MapEditor.LoadMap(String filename, Format format) in C:\Users\Cassio\source\repos\MapEditor\MapEditor.cs:line 751

[MapEditor.log](https://github.com/oldnapalm/MapEditor/files/7850497/MapEditor.log)
[ScriptHookVDotNet.log](https://github.com/oldnapalm/MapEditor/files/7850498/ScriptHookVDotNet.log)
![Screenshot (78)](https://user-images.githubusercontent.com/97489680/149038485-86f7d7f3-81ca-4cb1-92e0-2aeccd114a4d.png)
![Screenshot (79)](https://user-images.githubusercontent.com/97489680/149038505-49b0a365-46a9-42bf-abca-db583124e8f9.png)
![Screenshot (80)](https://user-images.githubusercontent.com/97489680/149038517-179ab838-f46f-45e4-8e00-aae89457e5d8.png)

**Comment by oldnapalm** [comment]
I see. I think this is due to an incompatibility between ScriptHookV and RagePluginHook.

I prevented the error at line 751 (`PropStreamer.ActiveRelationships.Add(pedid.Handle, o.Relationship)`) by adding a check before that line (`if (!PropStreamer.ActiveRelationships.ContainsKey(pedid.Handle))`) but I don't understand why it only happens when RagePluginHook is loaded.

Probably the misplaced objects are due to the same incompatibility. At the moment I have no idea on how do fix or workaround it, will let you know if I think of something.

**Comment by CptLevi23** [comment]
ok, thanks for the help, could I give donation to you if you do figure out tge work around. I feel since this is hard to do. I need to pay you.

**Comment by Michael21107** [comment]
@oldnapalm may I suggest you re-open this issue so someone else may see it easier and maybe provide a fix?

**Comment by oldnapalm** [comment]
> @oldnapalm may I suggest you re-open this issue so someone else may see it easier and maybe provide a fix?

Honestly I don't think that having this issue open will help to get it fixed. If you want visibility it's probably more effective to open an issue in the [original repo](https://github.com/Guad/MapEditor).

**Comment by Michael21107** [comment]
@oldnapalm up to you, just someone may see this too as this is the only active fork
