### ISSUE TITLE
F7 doesn't open map editor

### ISSUE THREAD

**Issue by tedomedo** [oldnapalm/MapEditor#4]
I was using map editor from https://www.gta5-mods.com/scripts/map-editor before. F7 opened it. 
I have your map editor 2.15.zip now,  i unzipped folder MapEditor-2.15 into scripts folder. F7 doesn't show anything. Did you select another key? 
I unzipped both 2205cd-MapEditor-2.15.zip from GTA V mods site and MapEditor-2.15.zip from github but F7 again didn't open map editor.

**Comment by oldnapalm** [comment]
The key is the same (F7).

Attach your ScriptHookVDotNet.log from GTA 5 folder.

Just extract all the zip contents to your scripts folder. The files from GitHub and GTA5-mods are identical.

**Comment by tedomedo** [comment]
Ok, delete my dumb post.
