### ISSUE TITLE
Map Editor 2.15 has a bug (or i don't use it well) about pitch angles

### ISSUE THREAD

**Issue by tedomedo** [oldnapalm/MapEditor#5]
I did screen record and uploaded video, here is URL: 
https://www.dropbox.com/scl/fi/i1p2uuk9i4q3yw9zaa78v/Grand-Theft-Auto-V-2023-11-06-17-48-29.mp4?rlkey=t4ek6b96vhve8tn4g45hun1rc

I placed property stunt_bblock_xl2. I set pitch angle -5 so that this property had the same angle as floor, then roll angle 80, but this changed both pitch and yaw angle. The same happened after i used left shift for rotation, keys for pitch mostly affected yaw angle.  Why is this happening? Explain me how to get the wanted angle. This never happened in version 2.13.

**Comment by oldnapalm** [comment]
Look https://github.com/oldnapalm/MapEditor/commit/f835d7f52921f1974c07141ca27464f8c6f72197

I changed that because the previous code didn't work for me, I can't explain why, my best guess is it was due to different libraries versions.

If version 2.13 works better for you, just use it, no need to use this update.

**Comment by tedomedo** [comment]
In 2.13 i have to enter both pitch and roll angle into the same box. E. g. for angles -5 and 80 i would enter 80 or -80 (entered negative number was shown as positive and vice versa) into pitch box, then 5 or -5 into pitch box again. Or first -5 into roll box and then 80 into roll box again.

**Comment by oldnapalm** [comment]
And does that make sense to you?

https://simple.wikipedia.org/wiki/Pitch,_yaw,_and_roll

https://github.com/oldnapalm/MapEditor/assets/38410858/dead1c9c-c546-46be-8687-b287407b9886

**Comment by tedomedo** [comment]
Sorry, my and your posting about positive or negative number is mostly off-topic. 
With map editor 2.15 i opened my map created with 2.13 version, i saw everything the same as before while i was using 2.13. I clicked something and i saw right angles, e. g. pitch 20 and roll 40. But when i changed any angle, it fucked up all angles.  So for editing or creating maps, i will use 2.13. For creating community race or for changing texture, i will load map with 2.15 and save.

**Comment by oldnapalm** [comment]
2.13 is the original by Guadmaz (https://github.com/Guad/MapEditor), I can't change it.

Please test

[MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/13297632/MapEditor.zip)

**Comment by oldnapalm** [comment]
https://github.com/oldnapalm/MapEditor/assets/38410858/e2bff197-5688-416e-8d65-68cd95f990df

**Comment by oldnapalm** [comment]
Fixed in https://github.com/oldnapalm/MapEditor/releases/tag/v2.16

**Comment by tedomedo** [comment]
I just tried, rotations work now. Thank you!

**Comment by tedomedo** [comment]
Sorry for bothering you but rotations for some objects doesn't work even in 2.16. One of these objects is stt_prop_track_speedup. 
![slika](https://github.com/oldnapalm/MapEditor/assets/52840688/1bec4796-224c-43de-893e-a2af8a02f8ef)
![slika](https://github.com/oldnapalm/MapEditor/assets/52840688/6ad23955-8259-4c7a-801c-64cbdb196854)
![slika](https://github.com/oldnapalm/MapEditor/assets/52840688/16fe1763-30a9-4557-82f2-8b217153c95f)
![slika](https://github.com/oldnapalm/MapEditor/assets/52840688/1b569f14-d375-445b-871d-8c99bfbe6eac)

**Comment by oldnapalm** [comment]
Try this please

[MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/13394763/MapEditor.zip)

**Comment by tedomedo** [comment]
What's different in this MapEditor.dll?
