### ISSUE TITLE
Peds don't hold their weapons !!

### ISSUE THREAD

**Issue by Soru1368** [oldnapalm/MapEditor#7]
i have a problem with my map editor !! when i set a gun for my peds they don't hold it !! i realized that the version of ScriptHookVDotNet2 is the issue, i mean in 3.4.0 and higher !! what's wrong ?!! 
[ScriptHookV.log](https://github.com/oldnapalm/MapEditor/files/15191278/ScriptHookV.log)
[ScriptHookVDotNet.log](https://github.com/oldnapalm/MapEditor/files/15191279/ScriptHookVDotNet.log)

**Comment by Soru1368** [comment]
[ScriptHookVDotNet.log](https://github.com/oldnapalm/MapEditor/files/15191268/ScriptHookVDotNet.log)

**Comment by oldnapalm** [comment]
Maybe in previous versions of SHVDN the weapon was selected by default after giving it to the ped. It should work now, select the weapon and press enter.

[MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/15193077/MapEditor.zip)

**Comment by Soru1368** [comment]
now the F7 doesn't work :) ! it seems that my map editor doesn't work properly with scripthookvdotnet 3.4.0 and higher !! i tried lots of versions and found that the problem is ScriptHookVDotNet2 !! when i use ScriptHookVDotNet.asi and ScriptHookVDotNet3 from 3.4.0 and higher with ScriptHookVDotNet2 from versions like 3.3.2 and lower, there wasn't any problem but when i use ScriptHookVDotNet2 from 3.4.0 and higher the problem with my map editor that i mentioned appears !!

**Comment by Soru1368** [comment]
> Maybe in previous versions of SHVDN the weapon was selected by default after giving it to the ped. It should work now, select the weapon and press enter.
> 
> [MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/15193077/MapEditor.zip)

now the F7 doesn't work :) ! it seems that my map editor doesn't work properly with scripthookvdotnet 3.4.0 and higher !! i tried lots of versions and found that the problem is ScriptHookVDotNet2 !! when i use ScriptHookVDotNet.asi and ScriptHookVDotNet3 from 3.4.0 and higher with ScriptHookVDotNet2 from versions like 3.3.2 and lower, there wasn't any problem but when i use ScriptHookVDotNet2 from 3.4.0 and higher the problem with my map editor that i mentioned appears !!

**Comment by Soru1368** [comment]
> Maybe in previous versions of SHVDN the weapon was selected by default after giving it to the ped. It should work now, select the weapon and press enter.
> 
> [MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/15193077/MapEditor.zip)

it worked :)))) THANK YOU !!

**Comment by oldnapalm** [comment]
I tested with this version and it works https://github.com/scripthookvdotnet/scripthookvdotnet/releases/tag/v3.6.0

You should see this in your log

```
[DEBUG] Loading assembly MapEditor.dll ...
[INFO] Found 2 script(s) in MapEditor.dll resolved to API 2.11.6.
```

**Comment by Soru1368** [comment]
> I tested with this version and it works https://github.com/scripthookvdotnet/scripthookvdotnet/releases/tag/v3.6.0
> 
> You should see this in your log
> 
> ```
> [DEBUG] Loading assembly MapEditor.dll ...
> [INFO] Found 2 script(s) in MapEditor.dll resolved to API 2.11.6.
> ```

but now i have another problem!! when i save a ped with a gun when i load the xml they still don't appear with the gun !! i should press enter to appear

**Comment by Soru1368** [comment]
> > I tested with this version and it works https://github.com/scripthookvdotnet/scripthookvdotnet/releases/tag/v3.6.0
> > You should see this in your log
> > ```
> > [DEBUG] Loading assembly MapEditor.dll ...
> > [INFO] Found 2 script(s) in MapEditor.dll resolved to API 2.11.6.
> > ```
> 
> but now i have another problem!! when i save a ped with a gun when i load the xml they still don't appear with the gun !! i should press enter to appear


[00:22:09] [DEBUG] Loading assembly MapEditor.dll ...
[00:22:09] [INFO] Found 2 script(s) in MapEditor.dll resolved to API 2.11.6.
[00:22:09] [DEBUG] Loading assembly NativeUI.dll ...
[00:22:09] [INFO] Found 1 script(s) in NativeUI.dll resolved to API 2.11.6.
[00:22:09] [DEBUG] Loading assembly NoMoreMissingBlips.dll ...
[00:22:09] [INFO] Found 1 script(s) in NoMoreMissingBlips.dll resolved to API 2.11.6.
[00:22:09] [DEBUG] Loading assembly PedFuncSquad.dll ...
[00:22:09] [INFO] Found 4 script(s) in PedFuncSquad.dll resolved to API 2.11.6.
[00:22:09] [DEBUG] Loading assembly SquadsManager.dll ...
[00:22:09] [INFO] Found 1 script(s) in SquadsManager.dll resolved to API 3.6.0.
[00:22:09] [DEBUG] Instantiating script AdvancedBodyguards ...
[00:22:11] [INFO] Started script AdvancedBodyguards.
[00:22:11] [DEBUG] Instantiating script YourMenu ...

**Comment by oldnapalm** [comment]
Yes, it needs to be selected also on load.

[MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/15193463/MapEditor.zip)

**Comment by Soru1368** [comment]
> Yes, it needs to be selected also on load.
> 
> [MapEditor.zip](https://github.com/oldnapalm/MapEditor/files/15193463/MapEditor.zip)

so you're doing the same thing with your peds because i didn't need to do that in the past !! everytime i loaded an xml peds would appear with their guns !!

**Comment by oldnapalm** [comment]
Like I said before, my best guess is that in previous versions of ScriptHookDotNet the weapon was selected automatically on give, now it needs to be selected. It should work on map load with the last file I posted above.

**Comment by Soru1368** [comment]
what you sent fixed one of the issues and thanks for that but i didn't have the problem that when i load an xml , Peds appear with no gun !! i didn't need to press enter everytime !

**Comment by Soru1368** [comment]
> Like I said before, my best guess is that in previous versions of ScriptHookDotNet the weapon was selected automatically on give, now it needs to be selected. It should work on map load with the last file I posted above.

what you sent fixed one of the issues and thanks for that but i didn't have the problem that when i load an xml , Peds appear with no gun !! i didn't need to press enter everytime !

**Comment by oldnapalm** [comment]
Using the latest version posted above it works for me, ped appears with gun on map load. If it doesn't work for you I have no idea, I suggest that you use the version which worked in the past, there's no reason to use my version if the old one worked better.

**Comment by Soru1368** [comment]
> Using the latest version posted above it works for me, ped appears with gun on map load. If it doesn't work for you I have no idea, I suggest that you use the version which worked in the past, there's no reason to use my version if the old one worked better.

i used it but and they don't appear with gun !! let me try it again maybe this time works

**Comment by Soru1368** [comment]
> > Using the latest version posted above it works for me, ped appears with gun on map load. If it doesn't work for you I have no idea, I suggest that you use the version which worked in the past, there's no reason to use my version if the old one worked better.
> 
> i used it but and they don't appear with gun !! let me try it again maybe this time works

PERFECT !! now they appear with the gun !! Tnx for  your time and attention !! appreciated
