### ISSUE TITLE
my game crashes with map editor when i create more than 100 peds !!

### ISSUE THREAD

**Issue by Soru1368** [oldnapalm/MapEditor#8]
i actually have two problems one is related to map editor and the other isn't ! i just wanna ask maybe you know whats wrong !! first issue is when i create a map and i put more than 100 peds, game starts to crash and i realized that in some certain areas it happens !! my second question is do you know why in director mode when i set peds density on none i still have some peds in the city ?! i have these on : heap adjuster, PackfileLimitAdjuster, and pedprop limit adjuster !!! i used gameconfig for increasing the peds and vehicles but i reinstalled the game and still have this issue !!

**Comment by oldnapalm** [comment]
I don't think it's a Map Editor issue. Just don't create more peds than your setup can handle.

**Comment by Soru1368** [comment]
> I don't think it's a Map Editor issue. Just don't create more peds than your setup can handle.

what's wrong with my setup ?! if you mean my pc can't handle it, i have 1070ti gtx,  core i7 6700k, 16g Ram !!! i don't think my pc is the problem besides after i used the map editor that you actually sent me couple of weeks ago this happened !! i had problem with peds that didn't hold their weapons then you sent me another version of map editor !! like i said in some areas i have this problem don't know why for example i have an xml with max 254 peds and this doesn't happen but when i put more than 90 peds around Michael's house, the game crashes !!

**Comment by oldnapalm** [comment]
My version is only an update to work with the latest version of ScriptHookVDotNet2.

If the original version allows you create more peds without problems, use it instead.

**Comment by Soru1368** [comment]
> My version is only an update to work with the latest version of ScriptHookVDotNet2.
> 
> If the original version allows you create more peds without problems, use it instead.

Can't !! if i use older versions then some mods won't work

**Comment by oldnapalm** [comment]
Unfortunately there's nothing I can do about that.

Have in mind that some crowded areas have more than 100 peds created by the game (ambient, scenario, mission, etc) and those are also counted, not only the ones you create.

![Captura de tela 2024-05-23 185412](https://github.com/oldnapalm/MapEditor/assets/38410858/c38b4f0a-3583-48d4-8eec-a43bd845d272)

**Comment by Soru1368** [comment]
> Unfortunately there's nothing I can do about that.
> 
> Have in mind that some crowded areas have more than 100 peds created by the game (ambient, scenario, mission, etc) and those are also counted, not only the ones you create.
> 
> ![Captura de tela 2024-05-23 185412](https://private-user-images.githubusercontent.com/38410858/333354356-c38b4f0a-3583-48d4-8eec-a43bd845d272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDE4NDUsIm5iZiI6MTcxNjUwMTU0NSwicGF0aCI6Ii8zODQxMDg1OC8zMzMzNTQzNTYtYzM4YjRmMGEtMzU4My00OGQ0LThlZWMtYTQzYmQ4NDVkMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDIxNTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZDkxM2NkMWE1NDhmZGIzZDEzYzM0YWMyNjg1ZmI1MDJkNjZjYTZjYTI0MmI1OTVkNDEyYmJmY2ZmYWZhN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V5X3Ftr0OSQTPWYrvDL-xEQNUolgBQN1XcsLuFZx71w)

i found sth interesting !! when i just put peds without guns, game is ok but when i set weapons for them it happens !! any thoughts ?!!

**Comment by oldnapalm** [comment]
No idea other than the obvious (weapons also use resources and there's probably a limit of how many can exist simultaneously).

**Comment by Soru1368** [comment]
> No idea other than the obvious (weapons also use resources and there's probably a limit of how many can exist simultaneously).

ok tnx

**Comment by Soru1368** [comment]
> No idea other than the obvious (weapons also use resources and there's probably a limit of how many can exist simultaneously).

hey sorry for taking your time again but do you know why, the lights insdie the the building are not working when i load a map with a building ?!!
